preload:
  - ApplicationController
  - ApiController

controllers:
  - path: /auth/reset
    controller: AuthPasswordResetController
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth/mfa/totp
    controller: AuthLoginTotpController
  - path: /auth
    controller: AuthLoginController

  - path: /penpal/waiting
    controller: PenpalWaitingController
  - path: /penpal/:ppid/correspondence/create
    controller: PenpalCorrespondenceCreateController
  - path: /penpal/:ppid/correspondence/:cid
    controller: PenpalCorrespondenceController
  - path: /penpal/:ppid
    controller: PenpalController

  - path: /account/mfa/recovery
    controller: AccountMfaRecoveryController
  - path: /account/mfa/totp
    controller: AccountMfaTotpController
  - path: /account/mfa
    controller: AccountMfaController
  - path: /account
    controller: AccountIndexController

  - path: /system/apikey
    controller: SystemApiKeyController

  - path: /system/roster
    controller: SystemVolunteerRosterController

  - path: /system/files
    controller: SystemFilesController
  - path: /system/files/:id
    controller: SystemFilesInspectController

  - path: /system/mass-email
    controller: SystemMassEmailController

  - path: /system/prison/create
    controller: SystemPrisonCreateController
  - path: /system/prison/:pid
    controller: SystemPrisonEditController
  - path: /system/prison
    controller: SystemPrisonController

  - path: /system/penpal
    controller: SystemPenpalController
  - path: /system/penpal/addressbook
    controller: SystemPenpalAddressBookController
  - path: /system/penpal/create
    controller: SystemPenpalCreateController
  - path: /system/penpal/relationship/create
    controller: SystemPenpalRelationshipCreateController
  - path: /system/penpal/relationship/:id/delete
    controller: SystemPenpalRelationshipDeleteController
  - path: /system/penpal/relationship/:id/correspondence/create
    controller: SystemPenpalRelationshipCorrespondenceCreateController
  - path: /system/penpal/relationship/:id/correspondence/:cid
    controller: SystemPenpalRelationshipCorrespondenceViewController
  - path: /system/penpal/relationship/:id/correspondence
    controller: SystemPenpalRelationshipCorrespondenceController
  - path: /system/penpal/relationship/:id
    controller: SystemPenpalRelationshipController
  - path: /system/penpal/:id/delete
    controller: SystemPenpalDeleteController
  - path: /system/penpal/:id/edit
    controller: SystemPenpalEditController
  - path: /system/penpal/:id/associate
    controller: SystemPenpalAssociateUserController
  - path: /system/penpal/:id
    controller: SystemPenpalViewController

  - path: /system/user
    controller: SystemUserController
  - path: /system/user/by-role
    controller: SystemUserByRoleController
  - path: /system/user/create
    controller: SystemUserCreateController
  - path: /system/user/:id/penpal-obj
    controller: SystemUserPenpalObjectController
  - path: /system/user/:id/disable
    controller: SystemUserDisableController
  - path: /system/user/:id/auth
    controller: SystemUserAuthenticationController
  - path: /system/user/:id/edit-profile
    controller: SystemUserEditProfileController
  - path: /system/user/:id/groups
    controller: SystemUserGroupsController
  - path: /system/user/:id/roles
    controller: SystemUserRolesController
  - path: /system/user/:id/roles/adv
    controller: SystemUserRolesAdvancedController
  - path: /system/user/:id
    controller: SystemUserViewController

  - path: /system/group
    controller: SystemGroupController
  - path: /system/group/create
    controller: SystemGroupCreateController
  - path: /system/group/:id/delete
    controller: SystemGroupDeleteController
  - path: /system/group/:id/roles
    controller: SystemGroupRolesController
  - path: /system/group/:id/remove-user
    controller: SystemGroupRemoveUserController
  - path: /system/group/:id
    controller: SystemGroupEditController

  - path: /system/configuration/announcements
    controller: SystemConfigurationAnnouncementsController
  - path: /system/configuration/site-org-name
    controller: SystemConfigurationSiteOrgNameController
  - path: /system/configuration/mail
    controller: SystemConfigurationMailController
  - path: /system/configuration/keys
    controller: SystemConfigurationKeysController
  - path: /system/configuration/filter
    controller: SystemConfigurationFilterController
  - path: /system/configuration
    controller: SystemConfigurationController

  - path: /system/debugging/emailpreview
    controller: SystemDebuggingEmailTemplatePreviewController
  - path: /system/debugging
    controller: SystemDebuggingController

  - path: /system/jobqueue
    controller: SystemJobQueueController
  - path: /system
    controller: SystemIndexController

  - path: /language
    controller: LanguageController

  - path: /filedl
    controller: FileDownloadController
  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController

  - path: /api/meta
    controller: ApiMetaController
  - path: /api/prisons
    controller: ApiPrisonsController
