preload:
  - ApplicationController

controllers:
  - path: /auth/reset
    controller: AuthPasswordResetController
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth
    controller: AuthLoginController

  - path: /account/twofactor
    controller: AccountTwoFactorController
  - path: /account
    controller: AccountIndexController

  - path: /system/files
    controller: SystemFilesController
  - path: /system/files/:id
    controller: SystemFilesInspectController

  - path: /system/penpal
    controller: SystemPenpalController
  - path: /system/penpal/create
    controller: SystemPenpalCreateController
  - path: /system/penpal/relationship/create
    controller: SystemPenpalRelationshipCreateController
  - path: /system/penpal/relationship/:id/delete
    controller: SystemPenpalRelationshipDeleteController
  - path: /system/penpal/relationship/:id/correspondence/create
    controller: SystemPenpalRelationshipCorrespondenceCreateController
  - path: /system/penpal/relationship/:id/correspondence/:cid
    controller: SystemPenpalRelationshipCorrespondenceViewController
  - path: /system/penpal/relationship/:id/correspondence
    controller: SystemPenpalRelationshipCorrespondenceController
  - path: /system/penpal/relationship/:id
    controller: SystemPenpalRelationshipController
  - path: /system/penpal/:id/delete
    controller: SystemPenpalDeleteController
  - path: /system/penpal/:id/edit
    controller: SystemPenpalEditController
  - path: /system/penpal/:id/associate
    controller: SystemPenpalAssociateUserController
  - path: /system/penpal/:id
    controller: SystemPenpalViewController

  - path: /system/user
    controller: SystemUserController
  - path: /system/user/:id/penpal-obj
    controller: SystemUserPenpalObjectController
  - path: /system/user/:id/disable
    controller: SystemUserDisableController
  - path: /system/user/:id/auth
    controller: SystemUserAuthenticationController
  - path: /system/user/:id/edit-profile
    controller: SystemUserEditProfileController
  - path: /system/user/:id/roles
    controller: SystemUserRolesController
  - path: /system/user/:id/roles/adv
    controller: SystemUserRolesAdvancedController
  - path: /system/user/:id
    controller: SystemUserViewController

  - path: /system/configuration/site-org-name
    controller: SystemConfigurationSiteOrgNameController
  - path: /system/configuration/mail
    controller: SystemConfigurationMailController
  - path: /system/configuration/keys
    controller: SystemConfigurationKeysController
  - path: /system/configuration
    controller: SystemConfigurationController

  - path: /system/debugging/emailpreview
    controller: SystemDebuggingEmailTemplatePreviewController
  - path: /system/debugging
    controller: SystemDebuggingController
  - path: /system
    controller: SystemIndexController

  - path: /language
    controller: LanguageController

  - path: /filedl
    controller: FileDownloadController
  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
