preload:
  - ApplicationController

controllers:
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth
    controller: AuthLoginController

  - path: /account/twofactor
    controller: AccountTwoFactorController
  - path: /account
    controller: AccountIndexController

  - path: /system/user
    controller: SystemUserController
  - path: /system/user/:id/disable
    controller: SystemUserDisableController
  - path: /system/user/:id/auth
    controller: SystemUserAuthenticationController
  - path: /system/user/:id/edit-profile
    controller: SystemUserEditProfileController
  - path: /system/user/:id
    controller: SystemUserViewController
  - path: /system/configuration/site-org-name
    controller: SystemConfigurationSiteOrgNameController
  - path: /system/configuration/keys
    controller: SystemConfigurationKeysController
  - path: /system/configuration
    controller: SystemConfigurationController
  - path: /system/debugging
    controller: SystemDebuggingController
  - path: /system
    controller: SystemIndexController

  - path: /language
    controller: LanguageController

  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
